# Generated by Django 5.2.8 on 2025-11-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('reports_to', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'open'), ('dismissed', 'dismissed')], default='open', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.employee')),
            ],
        ),
    ]
